version: "3.1"
services:
  sharing:
    image: sharing
    build: .
    links:
      - sharingDB
    depends_on:
      - sharingDB
    ports:
      - "8080:80"

  sharingDB:
    image: postgres
    environment:
      - POSTGRES_USER=sharingDB
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgresql/data