version: "3.1"
services:
  sharingAPP:
    image: sharing
    build: .
    links:
      - propay
      - h2DB
    depends_on:
      - propay
      - h2DB
    ports:
      - "8080:8080"

  propay:
    image: propra/propay:latest
    volumes:
      - propay:/code/data

  h2DB:
    image: oscarfonts/h2
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data:
  propay:
