version: "3.1"
services:
  sharingAPP:
    image: sharing
    build: .
    links:
      - sharingDB
      - propay
    depends_on:
      - sharingDB
      - propay
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static

  sharingDB:
    image: postgres
    environment:
      - POSTGRES_USER=sharingDB
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  propay:
    image: propra/propay:latest
    volumes:
      - ./data/propay:/code/data